/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Capa_Presentacion;

import Capa_Logica.Empresa;
import java.awt.Color;
import java.awt.Toolkit;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author PC 
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public static int in;
    double precioU = 0;
    public static ArrayList<Empresa> lista = new ArrayList<>();
    Empresa ler = new Empresa();
    public MenuPrincipal() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/engranaje.png")));
        getContentPane().setBackground(new Color(255,255,255));
        lista.clear();
        ler.Lectura_Ventas(lista);
        inicializar_datos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        btnStock = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnSalirX = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cbProducto = new javax.swing.JComboBox<>();
        cbCantidad = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barra.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 10, 424));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("@2022 The Ferreteria Company||Todos los derechos Reservados");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 154, 150));

        btnUsuario.setBackground(new java.awt.Color(255, 166, 0));
        btnUsuario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario.setText("Usuario");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, -1));

        btnConfiguracion.setBackground(new java.awt.Color(255, 166, 0));
        btnConfiguracion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnConfiguracion.setForeground(new java.awt.Color(255, 255, 255));
        btnConfiguracion.setText("Administrador");
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 140, -1));

        btnStock.setBackground(new java.awt.Color(255, 166, 0));
        btnStock.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnStock.setForeground(new java.awt.Color(255, 255, 255));
        btnStock.setText("Stock");
        btnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockActionPerformed(evt);
            }
        });
        getContentPane().add(btnStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 140, -1));

        btnSalir.setBackground(new java.awt.Color(255, 166, 0));
        btnSalir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 140, -1));

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Producto", "Precio", "Cantidad", "Fecha"
            }
        ));
        tblVentas.setRowHeight(30);
        jScrollPane1.setViewportView(tblVentas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, 180));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Producto:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Precio:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Cantidad:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Codigo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Fecha:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, 20));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("INTERFAZ DE VENTAS");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        txtPrecio.setEditable(false);
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 150, -1));

        txtCodigo.setEditable(false);
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 150, -1));

        txtFecha.setEditable(false);
        txtFecha.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 150, -1));

        btnNuevo.setBackground(new java.awt.Color(255, 166, 0));
        btnNuevo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorderPainted(false);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 80, -1));

        btnSalirX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png"))); // NOI18N
        btnSalirX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirXActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalirX, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 20, 19));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/herraP.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, 40));

        cbProducto.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------Seleccionar------", "Serrucho", "Alicate", "Llave inglesa", "Destornillador", "Martillo", "Cable" }));
        cbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProductoActionPerformed(evt);
            }
        });
        getContentPane().add(cbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 150, -1));

        cbCantidad.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(cbCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 150, -1));

        btnAgregar.setBackground(new java.awt.Color(255, 166, 0));
        btnAgregar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorderPainted(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 80, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 166, 0));
        btnEliminar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 80, -1));

        btnConsultar.setBackground(new java.awt.Color(255, 166, 0));
        btnConsultar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.setBorderPainted(false);
        btnConsultar.setEnabled(false);
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 80, -1));

        btnRegresar.setBackground(new java.awt.Color(255, 166, 0));
        btnRegresar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inicializar_datos(){
        for(int i=1; i<101; i++){
            cbCantidad.addItem(i + "");
        }
        //Obtenemos y mostramos la fecha
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        txtFecha.setText(dtf.format(LocalDateTime.now()));
        //Obtenermos y mostramos el codigo de compra
        codigo_aleatorio();
        //Mostramos los datos en la tabla
        mostrar_tabla();
    }
    public void mostrar_tabla(){
        
        String matris[][] = new String[lista.size()][5];
        
        for(int i=0; i<lista.size(); i++){
            matris[i][0] = lista.get(i).getCodigo();
            matris[i][1] = lista.get(i).getProducto();
            matris[i][2] = lista.get(i).getPrecio();
            matris[i][3] = lista.get(i).getCantidad();
            matris[i][4] = lista.get(i).getFecha();
        }
        
        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "Codigo", "Producto", "Precio", "Cantidad", "Fecha"
            }
        ));
    }
    
    public LocalDate convertir_a_LocalDate(Date dateToConvert) {
        return dateToConvert.toInstant()
          .atZone(ZoneId.systemDefault())
          .toLocalDate();
    }
    
    public Date ADate(LocalDate currentLocalDate) {
        // Obteniendo la hora del sistema
	ZoneId systemTimeZone = ZoneId.systemDefault();
	// conviritiendo LocalDateTime a ZonedDateTime con el sistema timezone
	ZonedDateTime zonedDateTime = currentLocalDate.atStartOfDay(systemTimeZone);
        // convirtiendo ZonedDateTime a Date usando Date.from() y ZonedDateTime.toInstant()
	Date utilDate = Date.from(zonedDateTime.toInstant());
                
        return utilDate;
  }
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalirXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirXActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirXActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        Perfil per = new Perfil();
        per.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockActionPerformed
        Stock st = new Stock();
        this.setVisible(false);
        st.setVisible(true);
    }//GEN-LAST:event_btnStockActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        cbProducto.setSelectedIndex(0);
        txtPrecio.setText("");
        cbCantidad.setSelectedIndex(0);
        txtCodigo.setText("");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void cbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProductoActionPerformed
        if(cbProducto.getSelectedIndex()==0){
            precioU = 0;
        }
        else if(cbProducto.getSelectedIndex()==1){
            precioU = 32.11;
        }
        else if(cbProducto.getSelectedIndex()==2){
            precioU = 15.07;
        }
        else if(cbProducto.getSelectedIndex()==3){
            precioU = 24.57;
        }
        else if(cbProducto.getSelectedIndex()==4){
            precioU = 18.83;
        }
        else if(cbProducto.getSelectedIndex()==5){
            precioU = 21.99;
        }
        else if(cbProducto.getSelectedIndex()==6){
            precioU= 33.66;
        }
        else if(cbProducto.getSelectedIndex()==7){
            precioU = 26.77;
        }
        else if(cbProducto.getSelectedIndex()==8){
            precioU = 76.33;
        }
        else if(cbProducto.getSelectedIndex()==9){
            precioU = 24.11;
        }
        Precio();
    }//GEN-LAST:event_cbProductoActionPerformed

    private void cbCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCantidadActionPerformed
        if(cbProducto.getSelectedIndex()==0){
            precioU = 0;
        }
        Precio();      
    }//GEN-LAST:event_cbCantidadActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if(cbProducto.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Por favor eliga el producto a comprar.");
        }else{
            Empresa temp = new Empresa((String)cbProducto.getSelectedItem(), txtCodigo.getText(), txtPrecio.getText(),(String)cbCantidad.getSelectedItem() , txtFecha.getText());
            lista.add(temp);
            temp.Guardar_Ventas(lista);
            mostrar_tabla();
            codigo_aleatorio();
            JOptionPane.showMessageDialog(null, "Compra registrada correctamente.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String respuesta = JOptionPane.showInputDialog("Ingrese el codigo de la compra a eliminar:");
        if(ler.consultar(respuesta, lista)==true){
            in = ler.indice();
            lista.remove(in);
            mostrar_tabla();
            ler.Guardar_Ventas(lista);
        }else{
            JOptionPane.showMessageDialog(null, "El codigo ingresado es incorrecto.", "Problema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String respuesta = JOptionPane.showInputDialog("Ingrese el codigo de la compra a consultar:");
        if(ler.consultar(respuesta, lista)==true){
            in = ler.indice();
            Consulta con = new Consulta();
            con.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "El codigo ingresado es incorrecto", "Problema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
        if(ler.nivel.equals("Administrador")){
            btnConsultar.setEnabled(true);
            btnEliminar.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Modo Administrador activado");
        }else{
            JOptionPane.showMessageDialog(null, "Bloqueado, este modo solo es permitido para nivel administrador.", "No permitido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
        Login leg = new Login();
        leg.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void Precio(){      
        double precioFinal = precioU* Integer.parseInt((String)cbCantidad.getSelectedItem());
        precioFinal = Math.round(precioFinal*100)/100d;
        txtPrecio.setText(precioFinal + "$");
    }
    
    private void codigo_aleatorio(){
        int cod = ler.codigo_compra(lista);
        txtCodigo.setText(cod + "");      
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalirX;
    private javax.swing.JButton btnStock;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JComboBox<String> cbCantidad;
    private javax.swing.JComboBox<String> cbProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
